package petstore.api.actions;

import org.hamcrest.Matchers;
import starter.petstore.Pet;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import io.restassured.http.ContentType;
import io.restassured.mapper.ObjectMapperType;
import static net.serenitybdd.rest.SerenityRest.given;
import net.serenitybdd.core.steps.UIInteractions;

import static net.serenitybdd.rest.SerenityRest.*;

// We extend the UIInteractions class that comes with the Serenity BDD to help us interact with APIs
public class PetApiActions extends UIInteractions {

    @Given("Kitty is available in the pet store")
    // Since we want to user the ID generated by the API in our upcoming step, we return the ID as a Long return value
    public Long givenKittyIsAvailableInPetStore() {
        Pet pet = new Pet("Kitty", "available");

        return given()
                .baseUri("https://petstore.swagger.io")
                .basePath("/v2/pet")
                .body(pet, ObjectMapperType.GSON)
                .accept(ContentType.JSON)
                .contentType(ContentType.JSON).post().getBody().as(Pet.class, ObjectMapperType.GSON).getId();
    }

    @When("I ask for a pet using Kitty's ID: {0}")
    public void whenIAskForAPetWithId(Long id) {
        // in this get ethod call, the 'baseUri' and 'basePath' from the given() section is reused.
        // so you don't have to repeat those details in this method.
        when().get("/" + id);
    }

    @Then("I get Kitty as result")
    public void thenISeeKittyAsResult() {
        then().body("name", Matchers.equalTo("Kitty"));
    }
}
